labelTaints:
  - taint:
      key: testKey
      value: testValue
      effect: NoSchedule
    selector:
      key: maybit.de/taint-me
  - taint:
      key: second
      value: testValue
      effect: NoSchedule
    selector:
      key: maybit.de/taint-me-please
      value:  foo
ignoreLabel:
  key: ignore
  value: test
