name: Rust Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"  ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  linting:
   runs-on: ubuntu-latest
   steps:
   - uses: dtolnay/rust-toolchain@stable
     with:
       components: clippy,rustfmt
   - uses: actions/checkout@v4
   - name: Check formatting
     run: cargo fmt --check
   - name: Lint
     run: cargo clippy --all-targets --all-features
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --locked --verbose
    - name: Run tests
      run: cargo test --locked --verbose
